name: request_builder_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  request_builder:
    path: ../
  dio: ^5.2.1+1
  http: ^0.13.4
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
